### ISSUE TITLE
Generate error report - send errors by mail

### ISSUE THREAD

**Issue by JaleelNazir** [nuxt/youch#2]
Hello any help for this.

I'm doing app by Nuxt. I want to monitor all errors and server crash. Help me to how to do it.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/youch/issues/c1">#c1</a>)</em></sub></div>

**Comment by nikkanetiya** [comment]
Use some vendor like https://sentry.io/ I presonally using sentry for small projects.
